---
- hosts: galaxyservers
  become: true 
  vars:
    slurm_roles: ['controller', 'exec']
  vars_files:
   - "secret_group_vars/galaxyservers.yml"
  pre_tasks:
    - name: install psycopg2
      package:
        name: ['git', 'python-virtualenv', 'make','python-psycopg2','mercurial']
  handlers:
    - name: Restart Galaxy
      supervisorctl:
        name: galaxy
        state: restarted
  roles:
    - geerlingguy.git
    - galaxyproject.postgresql
    - role:  natefoo.postgresql_objects
      become: true
      become_user: postgres
    - galaxyproject.galaxy
    - uchida.miniconda
    - geerlingguy.pip
    - usegalaxy-eu.supervisor
    - galaxyproject.nginx
    - galaxyproject.repos
    - galaxyproject.slurm

  post_tasks:
    - name: Copy welcome.html
      copy:
        src: files/galaxy/welcome.html
        dest: "{{ vault_galaxy_root }}/galaxy/server/static/"
    - name: Install slurm-drmaa
      package:
        name: slurm-drmaa1
    - name: Copy slurm update for ilifu issues (adds a PATH update)
      copy:
        src: files/galaxy/config/slurm.py
        dest: "{{ vault_galaxy_root }}/galaxy/server/lib/galaxy/jobs/runners/util/cli/job/"

